### ISSUE TITLE
project "save as ..." always save in default location

### ISSUE THREAD

**Issue by d-anuwat** [GPUOpen-Tools/Compressonator#56] opened 2018-09-11 03:32 UTC
when perform "save as " project,  saving project file always save in default location even select to save in different location,

**Comment by xooiamd** [comment] 2018-09-12 23:00
hi @d-anuwat , thanks for reporting this issue. The issue seems to be caused by QFileInfo isWriteable() function always returns false for every file path location. Thus, a fix has been made in the commit [095483b ](https://github.com/GPUOpen-Tools/Compressonator/commit/095483b00fafb1f2d3443cda7cc47bb19ff18498) . Please grab this and run BuildGUI.bat to generate the binary. A built binary with the fix will be posted in upcoming release. Please let us know if you still encounter further issues. Thanks.

**Closed** 2019-01-03 15:24 UTC
