### ISSUE TITLE
Incorrect DDS file generated when compressing BC6H cubemap [4.2.5185]

### ISSUE THREAD

**Issue by sherief** [GPUOpen-Tools/compressonator#196] opened 2021-12-05 15:12 UTC
When compressing a an RGBA16F cubemap, the resulting files has 36 faces for each mip level instead of 6.

Input and output files attached:
[grace_cross_mmp_ABGR16F.zip](https://github.com/GPUOpen-Tools/compressonator/files/7656201/grace_cross_mmp_ABGR16F.zip)

Command line and output:
```compressonatorcli.exe  "./grace_cross_mmp_ABGR16F.dds" "./results/grace_cross_mmp_ABGR16F_DDS_BC6H_2.DDS"  -fd BC6H  -miplevels 7  -NumThreads 12 
Source Texture size = 0 Bytes, width = 256 px  height = 256 px
Destination Texture size = 65536 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 256 px  height = 256 px
Destination Texture size = 65536 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 256 px  height = 256 px
Destination Texture size = 65536 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 256 px  height = 256 px
Destination Texture size = 65536 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 256 px  height = 256 px
Destination Texture size = 65536 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 256 px  height = 256 px
Destination Texture size = 65536 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 128 px  height = 128 px
Destination Texture size = 16384 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 128 px  height = 128 px
Destination Texture size = 16384 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 128 px  height = 128 px
Destination Texture size = 16384 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 128 px  height = 128 px
Destination Texture size = 16384 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 128 px  height = 128 px
Destination Texture size = 16384 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 128 px  height = 128 px
Destination Texture size = 16384 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 64 px  height = 64 px
Destination Texture size = 4096 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 64 px  height = 64 px
Destination Texture size = 4096 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 64 px  height = 64 px
Destination Texture size = 4096 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 64 px  height = 64 px
Destination Texture size = 4096 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 64 px  height = 64 px
Destination Texture size = 4096 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 64 px  height = 64 px
Destination Texture size = 4096 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 32 px  height = 32 px
Destination Texture size = 1024 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 32 px  height = 32 px
Destination Texture size = 1024 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 32 px  height = 32 px
Destination Texture size = 1024 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 32 px  height = 32 px
Destination Texture size = 1024 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 32 px  height = 32 px
Destination Texture size = 1024 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 32 px  height = 32 px
Destination Texture size = 1024 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 16 px  height = 16 px
Destination Texture size = 256 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 16 px  height = 16 px
Destination Texture size = 256 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 16 px  height = 16 px
Destination Texture size = 256 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 16 px  height = 16 px
Destination Texture size = 256 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 16 px  height = 16 px
Destination Texture size = 256 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 16 px  height = 16 px
Destination Texture size = 256 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 8 px  height = 8 px
Destination Texture size = 64 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 8 px  height = 8 px
Destination Texture size = 64 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 8 px  height = 8 px
Destination Texture size = 64 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 8 px  height = 8 px
Destination Texture size = 64 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 8 px  height = 8 px
Destination Texture size = 64 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 8 px  height = 8 px
Destination Texture size = 64 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 4 px  height = 4 px
Destination Texture size = 16 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 4 px  height = 4 px
Destination Texture size = 16 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 4 px  height = 4 px
Destination Texture size = 16 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 4 px  height = 4 px
Destination Texture size = 16 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 4 px  height = 4 px
Destination Texture size = 16 Bytes   Resulting compression ratio = 0.00:1
Source Texture size = 0 Bytes, width = 4 px  height = 4 px
Destination Texture size = 16 Bytes   Resulting compression ratio = 0.00:1
Compressed to BC6H with 42 iteration(s) in 2.245 seconds
Total time taken (includes file I/O): 2.246 seconds
Done Processing
Processed in 2.28 seconds```

**Comment by denislevesqueAMD** [comment] 2023-07-07 16:30
I'm not sure what the issue is here. The input image has 7 mipmap levels per cubemap face, and from the output here Compressonator processed 42 images (6 faces * 7 mipmap levels). I even tried to test myself using both older and newer versions of Compressonator, but it all looked correct to me.

Since this was reported quite a while ago we might just want to close this issue. Unless @sherief happens to remember more details about the issue.

**Comment by sherief** [comment] 2023-07-17 11:38
Loading the output file from the attached .zip in Renderdoc shows the following: 
![image](https://github.com/GPUOpen-Tools/compressonator/assets/1711646/ffda08e3-dc73-49bb-aa5a-5daebe0a0fa7)
Under the "Slice/Face" combo box there's six instances of six faces each. The input file only shows one instance of six faces:
![image](https://github.com/GPUOpen-Tools/compressonator/assets/1711646/0086b71d-373d-4d33-a655-4a0cfb356922)

In the former file, all cubemap faces other than the first six show as black.

**Comment by denislevesqueAMD** [comment] 2023-07-19 17:37
@mosra Thanks for the suggestion! We'll see about implementing this fix in the near future.

**Closed** 2024-06-19 13:30 UTC
Labels: bug
