### ISSUE TITLE
BC7 color ramp interpolation

### ISSUE THREAD

**Issue by lexaknyazev** [GPUOpen-Tools/Compressonator#36] opened 2018-01-04 20:44 UTC
Generation of color ramp uses different math than MSDN example. 

Compare:
https://github.com/GPUOpen-Tools/Compressonator/blob/70d7d78f309f762b3c65fd112c2aa06e68ac06c6/Compressonator/Source/Codec/BC7/BC7_utils.cpp#L131-L142

and (from [here](https://msdn.microsoft.com/en-us/library/windows/desktop/hh308953(v=vs.85).aspx#decoding_the_bc7_format)):
```
UINT8 interpolate(UINT8 e0, UINT8 e1, UINT8 index, UINT8 indexprecision)
{
    if(indexprecision == 2)
        return (UINT8) (((64 - aWeights2[index])*UINT16(e0) + aWeights2[index]*UINT16(e1) + 32) >> 6);
    else if(indexprecision == 3)
        return (UINT8) (((64 - aWeights3[index])*UINT16(e0) + aWeights3[index]*UINT16(e1) + 32) >> 6);
    else // indexprecision == 4
        return (UINT8) (((64 - aWeights4[index])*UINT16(e0) + aWeights4[index]*UINT16(e1) + 32) >> 6);
}
```

The difference is that MSDN approach avoids floating-point calculations by using right-shift at the end.

This gives different results, e.g.:
```
mode 6:
color_bits = 7 + 1
ep0 = 1
ep1 = 82

index_bits = 4
index = 7 (30/64)

MSDN:
((64 - 30) * 1 + 30 * 82) >> 6 == 38

Compressonator:
1.0 * (1.0 - 0.46875) + 82.0 * 0.46875 + 0.5 == 39.46875
```

**Comment by NPCompress** [comment] 2018-01-05 15:36
Hi @lexaknyazev  
Thanks for bringing this to our attention. The Ramp Decode for BC7 will be investigated to determine its accuracy with our CPU decoder implementation vs that with GPU decode results using a number of sample blocks.

Once completed the results and any changes will be posted alongside this issue report.

**Comment by xooiamd** [comment] 2018-02-02 23:01
hi @lexaknyazev ,  using MSDN interpolation by bit shifting will affect the CPU decoder (as shown in the snapshot CPU_Decode_View image attached) and SSIM droped to 0.63. However, GPU decoder is fine ( as shown in the  GPU_Decode_View image attached) and SSIM is 0.99. 
![gpu_decode_view](https://user-images.githubusercontent.com/19152049/35758553-ac80deb0-0842-11e8-9f19-a5d2cdb90fbf.png)
![cpu_decode_view](https://user-images.githubusercontent.com/19152049/35758569-b64ffdfe-0842-11e8-8344-b7c4b2869ecd.png)
Therefore, definition "USE_HIGH_PRECISION_INTERPOLATION_BC7" has been added to BC7_Definitions.h file in the latest commit in master branch. You can uncomment this definition to use the bit shifting MSDN defined interpolation if you are only interested in GPU Decoder. Thanks!

**Comment by lexaknyazev** [comment] 2018-02-03 03:20
Hmmm,.. That looks strange.
First of all, my example above is incorrect since it lacks `+ 32` operation. So, results are actually the same (after `floor`):
```
MSDN:
((64 - 30) * 1 + 30 * 82 + 32) >> 6 == 39

Compressonator:
1.0 * (1.0 - 0.46875) + 82.0 * 0.46875 + 0.5 == 39.46875
```

Moreover, I couldn't find any other example that shows any difference between these formulas, so it's a bit suspicious that decoded images are that different.

**Comment by xooiamd** [comment] 2018-02-03 15:53
Hi @lexaknyazev , thanks for letting us know. we will look into the cause of the CPU and GPU decoder difference. I think the  ramp interpolation calculation is not the issue (there is no difference between those formulas), it might be caused by GPU and CPU choosing different mode (and thus different precision bit) for the block in decoding We will investigate further on the cause of the difference and posted here. Thanks!

**Comment by xooiamd** [comment] 2018-02-05 22:35
hi @lexaknyazev, the BC7 ramp calculation either by division and floor VS bit shifting produce same result. My attachment of the snapshot above are incorrect as I forgot the loop for cluster when calculating the ramp with bit shifting as shown by msdn. Both methods produce same result. Please see the latest commit [7ecb80f](https://github.com/GPUOpen-Tools/Compressonator/commit/7ecb80ff173bef8eae16666917c5f8bbfc8b7237) on the update. Thanks!

**Closed** 2018-02-05 22:39 UTC
