### ISSUE TITLE
BC1 artifacts

### ISSUE THREAD

**Issue by PanosK92** [GPUOpen-Tools/compressonator#163] opened 2021-03-08 11:32 UTC
Hello,

Thanks for working on this tool, it does a good job.

I've noticed some artifacts when I do BC1 compression that I'm not getting with other compression libraries.

I can reproduce the artifacts when using both the API and the GUI tool, using maximum quality.

I have attached a zip file that contains some comparisons.

My question is, is there a setting that I might be missing that can potentially help with these artifacts or is this something that could be improved in the next version?

Thanks,

[test.zip](https://github.com/GPUOpen-Tools/compressonator/files/6101064/test.zip)

**Comment by NPCompress** [comment] 2021-03-08 14:08
@PanosK92  Thanks for providing samples to validate the issue.

It can be reproduced using V4.1.5083 with the following settings:

![image](https://user-images.githubusercontent.com/18406717/110331377-09017800-7fed-11eb-99a4-e1c65d966502.png)

When setting the encoder to use HPC the issue is fixed.

![image](https://user-images.githubusercontent.com/18406717/110331818-9644cc80-7fed-11eb-87dc-38c27e8fa7a0.png)

CPU settings uses BC1 codec in CompressonatorLib SDK while the new HPC (performance optimized codecs) setting use CMP_Core SDK 

The BC1 CompressonatorLib SDK needs an update for next release.

**Comment by PanosK92** [comment] 2021-03-10 11:16
Thanks for the prompt reply,

Changing the encoder to HPC works with the GUI tool but not when using the Compressonator SDK.
Should I wait for the next release or is there some additional option that I might be missing?

Thanks

**Comment by NPCompress** [comment] 2021-03-10 14:43
@PanosK92  If CMP_Core is too low level code which processes on only 4x4 blocks, then you can also try the higher level API in Framework Lib which uses CMP_ProcessTexture() see Framework examples on how to use it.

**Comment by PanosK92** [comment] 2021-03-16 13:09
Thanks, I was able to bypass the glitchy pixels by using HPC with the framework API.

In case it's helpful, I encountered a small obstacle along the way, here is what it was and how I solved it.

The framework examples assume that you will be calling CMP_LoadTexture(), which populates a CMP_MipSet for you, which is what CMP_ProcessTexture() requires.

In my case, I needed to populate a CMP_MipSet directly from memory. After looking at the source of CMP_LoadTexture() I was able to do it myself, however, after calling CMP_ProcessTexture(), it failed. It turns out that CMP_LoadTexture() is calling CMP_RegisterHostPlugins(), which is essential since it fetches encoding function pointers from external plugins.

My solution was to do a dummy call to CMP_LoadTexture() before anything else.

**Comment by PanosK92** [comment] 2021-03-16 13:15
Hi,

Another question if you don't mind, does the Framework have a Compressonator equivalent way to set options like DXT1UseAlpha and AlphaThreshold or I'm better off going through the source code?

Thanks

**Comment by NPCompress** [comment] 2021-05-04 13:40
@PanosK92  
There is no interface in CMP_framework to set BC1(DXT1) settings directly, but there are some low level CMP_Core API settings. like SetChannelWeightsBC1(), SetAlphaThresholdBC1(), etc.. that can be made accessible in Framework API's for the next release.

**Comment by NPCompress** [comment] 2021-07-19 20:19
resolved in v4.2 release

**Closed** 2021-07-19 20:19 UTC
